#!/bin/bash

if [ -z "$CONFIG_DIR" ]; then
  export CONFIG_DIR="/Users/fernandoperez/.config/sketchybar"
fi

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"


##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

#sketchybar --bar position=top height=32 blur_radius=0 color=0x00000000 border_width=3 border_color=0xFF17400b corner_radius=20
sketchybar --bar position=top height=32 blur_radius=0 color=0x00000000

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  # padding_bottom=8
  # padding_top=0
  # icon.font="SF Pro:Semibold:15.0"
  icon.font="Hack Nerd Font:Regular:15.0"
  label.font="SF Pro:Semibold:15.0"
  #icon.color=$WHITE
  #label.color=$WHITE
  background.color=0x00000000

  icon.color=0xE5E5E5FF       # Blanco suave
  label.color=0xB0BEC5FF      # Gris claro


  background.corner_radius=5
  background.height=24
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Left Items #####
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh


##### Right Items #####
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/ram.sh


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
